#!/bin/bash

projectDir="/home/arline/go/src/MODE/"
dir="/home/arline/go/src/MODE/servers/backend/networking/proto"
pwd
protoc -I "$projectDir" -I "$dir/protos" "services.proto" --go_out=plugins=grpc:"$dir"/generated/generalservices
protoc -I "$projectDir" -I "$dir/protos" "database.proto" --go_out=plugins=grpc:"$dir"/generated/databaseservices
